-- ============================================================
-- AkoraHub - Patch Phase 41 : Contenu technique des matières premières
-- À exécuter une seule fois, APRÈS phase40_schema.sql : Supabase Dashboard
-- -> SQL Editor -> New query
--
-- Contexte (01/08) : plutôt que de laisser l'utilisatrice rédiger seule
-- ~190 fiches à partir de zéro, ce script remplit la description
-- technique + la précaution de sécurité de chaque matière première déjà
-- listée dans supabase/phase33_patch_raw_material_name_suggestions.sql
-- (rédigé par Claude à partir de connaissances chimiques/cosmétiques/
-- agroalimentaires générales et bien établies — pas une invention de
-- données propres à Akora Fanadiovana).
--
-- ⚠️ Volontairement PAS rempli ici : prix (`current_price`), usages liés
-- à un produit du catalogue (`raw_material_usages`) et conditionnement
-- (`raw_material_packaging`). Ce sont des données opérationnelles réelles
-- (coût fournisseur, formats effectivement stockés, dans quel produit
-- exact chaque matière est utilisée) que seule l'utilisatrice connaît —
-- les inventer serait dangereux dans une vraie application métier. À
-- ajouter au cas par cas depuis l'écran Admin (fiche éditeur).
--
-- Idempotent : `on conflict do nothing` grâce à la contrainte unique
-- ajoutée dans phase40 (business_unit_id, category_name, name) — relancer
-- ce script ne duplique rien et n'écrase pas une fiche déjà modifiée à
-- la main depuis l'app.
-- ============================================================

insert into public.raw_materials
  (business_unit_id, category_name, name, description, safety_note, stock_status)
select bu.id, v.category_name, v.name, v.description, v.safety_note, 'en_stock'
from (values
  ($$matieres-premieres$$, $$Tensioactifs$$, $$LABSA (Acide Sulfonique Lineaire)$$, $$Tensioactif anionique de synthèse, base de la majorité des détergents liquides et poudres modernes ; assure le pouvoir nettoyant et moussant principal.$$, $$Corrosif à l'état concentré — gants et lunettes obligatoires, rincer abondamment en cas de contact.$$),
  ($$matieres-premieres$$, $$Épaississants$$, $$CMC$$, $$Carboxyméthylcellulose, dérivé cellulosique hydrosoluble utilisé comme épaississant et stabilisant dans les liquides vaisselle, gels et shampooings.$$, null),
  ($$matieres-premieres$$, $$Charges Minérales$$, $$Sulfate de sodium$$, $$Sel minéral blanc utilisé comme charge de texture et agent de standardisation dans les poudres détergentes.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Bicarbonate de soude$$, $$Base douce (bicarbonate de sodium), utilisée comme abrasif léger et désodorisant dans les produits d'entretien ménager.$$, null),
  ($$matieres-premieres$$, $$Désinfectants$$, $$Hypochlorite de calcium 70%$$, $$Poudre chlorée concentrée servant de base à la fabrication d'eau de Javel et de désinfectants chlorés pour l'eau et les surfaces.$$, $$Oxydant et corrosif — dégage des vapeurs de chlore au contact de l'humidité ou d'acides ; stocker au sec, à l'écart des acides.$$),
  ($$matieres-premieres$$, $$Tensioactifs$$, $$Comperlan / Cocamide DEA$$, $$Agent moussant et épaississant dérivé de l'huile de coco, utilisé pour stabiliser et enrichir la mousse des shampooings et savons liquides.$$, null),
  ($$matieres-premieres$$, $$Chélatants$$, $$EDTA / Sequestrant$$, $$Agent chélatant qui capture les ions métalliques (calcium, magnésium, fer) pour prévenir le tartre et stabiliser la couleur/odeur des formulations.$$, null),
  ($$matieres-premieres$$, $$Huiles & Beurres Cosmétiques$$, $$Glycerine technique$$, $$Humectant et adoucissant polyvalent, utilisé dans les savons et cosmétiques pour retenir l'humidité et adoucir la peau.$$, null),
  ($$matieres-premieres$$, $$Huiles & Beurres Cosmétiques$$, $$Huile de coco$$, $$Huile végétale saponifiable, base classique de fabrication du savon et des shampooings solides.$$, null),
  ($$matieres-premieres$$, $$Tensioactifs$$, $$SLS$$, $$Sodium Lauryl Sulfate, tensioactif anionique puissant à fort pouvoir moussant et nettoyant, utilisé dans les shampooings et nettoyants ménagers.$$, $$Irritant possible pour peau/yeux sensibles à forte concentration — doser prudemment en cosmétique.$$),
  ($$matieres-premieres$$, $$Tensioactifs$$, $$SLES$$, $$Sodium Laureth Sulfate, version éthoxylée du SLS, moins irritante, base moussante des shampooings, gels douche et produits d'entretien.$$, null),
  ($$matieres-premieres$$, $$Tensioactifs$$, $$LAS$$, $$Linear Alkylbenzene Sulfonate, tensioactif anionique économique, principal nettoyant des détergents ménagers en poudre et liquide.$$, null),
  ($$matieres-premieres$$, $$Tensioactifs$$, $$AOS$$, $$Alpha Olefin Sulfonate, tensioactif puissant tolérant l'eau dure, utilisé dans les nettoyants industriels et détergents concentrés.$$, null),
  ($$matieres-premieres$$, $$Tensioactifs$$, $$SLSA$$, $$Sodium Lauryl Sulfoacetate, tensioactif doux sous forme de poudre, utilisé dans les bombes de bain et poudres lavantes.$$, null),
  ($$matieres-premieres$$, $$Tensioactifs$$, $$Sodium Coco-Sulfate$$, $$Tensioactif solide dérivé de l'huile de coco, alternative au SLS pour shampooings et savons solides.$$, null),
  ($$matieres-premieres$$, $$Tensioactifs$$, $$CAPB$$, $$Cocamidopropyl Betaine, tensioactif amphotère doux qui adoucit la mousse et réduit l'irritation des autres tensioactifs.$$, null),
  ($$matieres-premieres$$, $$Tensioactifs$$, $$Cocamidopropyl Hydroxysultaine$$, $$Tensioactif amphotère stabilisant de mousse, utilisé en complément dans les shampooings et gels douche doux.$$, null),
  ($$matieres-premieres$$, $$Tensioactifs$$, $$Decyl Glucoside$$, $$Tensioactif non-ionique doux d'origine végétale (glucose + alcool gras), adapté aux nettoyants pour peaux sensibles et bébés.$$, null),
  ($$matieres-premieres$$, $$Tensioactifs$$, $$Coco Glucoside$$, $$Tensioactif non-ionique doux dérivé de l'huile de coco et du glucose, utilisé dans les formules douces shampooing/gel douche.$$, null),
  ($$matieres-premieres$$, $$Tensioactifs$$, $$Lauryl Glucoside$$, $$Tensioactif non-ionique doux, nettoyant complémentaire dans les formules sans sulfate.$$, null),
  ($$matieres-premieres$$, $$Tensioactifs$$, $$Sodium Lauroyl Sarcosinate$$, $$Tensioactif doux dérivé d'acide aminé, utilisé dans les dentifrices et nettoyants doux pour sa faible irritation.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide citrique alimentaire$$, $$Acide organique naturel (agrumes), utilisé comme acidifiant et conservateur en agroalimentaire.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Bicarbonate de soude alimentaire$$, $$Agent levant et correcteur d'acidité de qualité alimentaire, utilisé en pâtisserie et boissons.$$, null),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Benzoate de sodium$$, $$Conservateur antimicrobien à large spectre, efficace en milieu acide (boissons, sauces, confitures).$$, null),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Sorbate de potassium$$, $$Conservateur anti-moisissures et anti-levures, largement utilisé dans les produits laitiers, boissons et pâtisseries.$$, null),
  ($$matieres-premieres$$, $$Charges Minérales$$, $$Sel alimentaire raffine$$, $$Chlorure de sodium raffiné, utilisé comme exhausteur de goût et conservateur traditionnel.$$, null),
  ($$matieres-premieres$$, $$Colorants$$, $$Colorants alimentaires certifies$$, $$Colorants approuvés pour l'alimentaire, utilisés pour standardiser ou intensifier la couleur d'un produit fini.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Aromes alimentaires$$, $$Concentrés aromatiques utilisés pour donner ou renforcer le goût d'un produit alimentaire.$$, null),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Acide ascorbique (Vitamine C)$$, $$Antioxydant naturel (Vitamine C), empêche le brunissement et l'oxydation des produits alimentaires.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Pectine$$, $$Gélifiant naturel extrait de fruits, utilisé pour la prise des confitures et sirops.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Gomme xanthane$$, $$Épaississant d'origine bactérienne (fermentation), stabilise la texture des sauces et boissons sans altérer le goût.$$, null),
  ($$matieres-premieres-peinture$$, $$Liants & Résines$$, $$Resines acryliques/vinyliques$$, $$Liant polymère qui forme le film de peinture et assure son adhérence et sa résistance.$$, null),
  ($$matieres-premieres-peinture$$, $$Pigments & Colorants$$, $$Pigments (oxydes de fer, TiO2)$$, $$Pigments minéraux apportant couleur et pouvoir couvrant (opacité) à la peinture.$$, null),
  ($$matieres-premieres-peinture$$, $$Solvants & Diluants$$, $$Solvants (White spirit, xylene)$$, $$Solvants pétroliers utilisés pour diluer la peinture et nettoyer le matériel d'application.$$, $$Inflammable — stocker à l'écart de toute flamme/source de chaleur, dans un local ventilé.$$),
  ($$matieres-premieres-peinture$$, $$Siccatifs & Conservateurs$$, $$Siccatifs (cobalt, manganese)$$, $$Sels métalliques qui accélèrent le séchage/durcissement de la peinture à l'huile en catalysant l'oxydation du liant.$$, $$Toxique à dose répétée — port de gants recommandé, éviter l'inhalation prolongée.$$),
  ($$matieres-premieres-peinture$$, $$Charges & Additifs$$, $$Charges minerales (carbonate calcium, talc)$$, $$Charges minérales inertes qui ajustent texture, opacité et coût de la peinture sans altérer sa tenue.$$, null),
  ($$matieres-premieres-peinture$$, $$Charges & Additifs$$, $$Dispersants/Agents mouillants$$, $$Additifs qui stabilisent la dispersion des pigments dans la peinture et évitent leur floculation/sédimentation.$$, null),
  ($$matieres-premieres-peinture$$, $$Charges & Additifs$$, $$Epaississants cellulosiques$$, $$Dérivés de cellulose qui ajustent la viscosité de la peinture pour une application homogène.$$, null),
  ($$matieres-premieres-peinture$$, $$Charges & Additifs$$, $$Anti-mousse$$, $$Additif qui élimine les bulles d'air piégées lors du mélange et de l'application de la peinture.$$, null),
  ($$matieres-premieres-peinture$$, $$Siccatifs & Conservateurs$$, $$Conservateurs (biocides peinture)$$, $$Biocides qui protègent la peinture en pot contre le développement de moisissures et de bactéries.$$, null),
  ($$matieres-premieres-peinture$$, $$Pigments & Colorants$$, $$Encre de base (colorants concentres)$$, $$Concentrés colorants utilisés comme base pour la fabrication d'encres.$$, null),
  ($$matieres-premieres$$, $$Solvants$$, $$Ethanol (alcool ethylique)$$, $$Alcool de fermentation ou de synthèse, solvant et désinfectant de base des gels hydroalcooliques et parfums.$$, $$Inflammable — tenir à l'écart de toute flamme.$$),
  ($$matieres-premieres$$, $$Solvants$$, $$Alcool isopropylique (IPA)$$, $$Solvant/désinfectant rapide à évaporation nette, utilisé pour la désinfection de surfaces et le nettoyage électronique.$$, $$Inflammable — ventiler les locaux lors d'un usage prolongé.$$),
  ($$matieres-premieres$$, $$Solvants$$, $$Methanol$$, $$Solvant industriel léger utilisé en antigel et fabrication d'encres.$$, $$Toxique, très dangereux — ne jamais utiliser dans un produit destiné au contact humain, ingestion mortelle même à faible dose.$$),
  ($$matieres-premieres$$, $$Solvants$$, $$Alcool benzylique$$, $$Alcool aromatique utilisé comme conservateur cosmétique et solvant de parfum.$$, $$Danger modéré — respecter les concentrations d'usage cosmétique reconnues.$$),
  ($$matieres-premieres$$, $$Solvants$$, $$Alcool cetylique$$, $$Alcool gras solide utilisé comme épaississant et agent de texture crémeuse dans les cosmétiques.$$, null),
  ($$matieres-premieres$$, $$Solvants$$, $$Propylene glycol$$, $$Solvant/humectant polyvalent, utilisé comme antigel doux et support d'arômes ou d'actifs.$$, null),
  ($$matieres-premieres$$, $$Solvants$$, $$Alcool denature$$, $$Éthanol rendu impropre à la consommation, utilisé pour le nettoyage industriel et la dilution de vernis.$$, $$Inflammable.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Soude caustique$$, $$Base forte (hydroxyde de sodium), utilisée pour la saponification, la neutralisation et le débouchage de canalisations.$$, $$Corrosif fort — gants et lunettes obligatoires ; réaction exothermique violente au contact de l'eau.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Potasse caustique$$, $$Base forte (hydroxyde de potassium), utilisée pour fabriquer les savons liquides/mous et certains cosmétiques.$$, $$Corrosif fort — mêmes précautions que la soude caustique.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Carbonate de sodium$$, $$Base douce (cristaux de soude), adoucit l'eau et renforce le pouvoir dégraissant des lessives et bases javellisées.$$, $$Danger modéré — irritant en poudre concentrée.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Ammoniaque$$, $$Solution aqueuse d'ammoniac, dégraissant puissant utilisé notamment pour le nettoyage des vitres.$$, $$Corrosif, vapeurs irritantes — ventiler impérativement, ne jamais mélanger avec de l'eau de Javel (dégagement toxique).$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Metasilicate de sodium$$, $$Base forte utilisée comme dégraissant industriel et agent anticorrosion dans certains nettoyants.$$, $$Corrosif.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Silicate de sodium$$, $$Renforce le pouvoir détergent et empêche la redéposition des salissures dans les lessives.$$, $$Danger modéré, irritant.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Chaux eteinte$$, $$Hydroxyde de calcium, utilisée pour le traitement de l'eau et la correction du pH.$$, $$Danger modéré — irritant pour peau et yeux.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide chlorhydrique$$, $$Acide fort, détartrant puissant et ajusteur de pH pour piscines.$$, $$Corrosif fort — dégage des vapeurs irritantes, jamais mélangé à l'eau de Javel.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide sulfurique$$, $$Acide fort industriel, utilisé en détartrage industriel et dans les batteries.$$, $$Très dangereux — réaction exothermique violente à l'eau ; toujours verser l'acide dans l'eau, jamais l'inverse.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide phosphorique$$, $$Acide utilisé comme détartrant, antirouille et additif alimentaire (acidifiant des colas).$$, $$Corrosif modéré.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide nitrique$$, $$Acide fort oxydant utilisé pour le nettoyage des métaux et la passivation de l'inox.$$, $$Corrosif fort, oxydant — vapeurs toxiques, manipulation sous ventilation.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide sulfamique$$, $$Acide solide stable, détartrant sûr d'usage pour surfaces sensibles (bouilloires, machines à café).$$, $$Danger modéré.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide citrique$$, $$Acide organique doux, détartrant écologique, conservateur et actif cosmétique (exfoliant léger).$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide acetique$$, $$Base du vinaigre, détartrant écologique et neutralisant doux.$$, $$Danger modéré concentré — vapeurs irritantes.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide lactique$$, $$Acide de fermentation utilisé comme exfoliant cosmétique doux et conservateur.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide oxalique$$, $$Détachant de rouille et agent de blanchiment du bois.$$, $$Toxique, usage encadré — port de gants obligatoire.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide borique$$, $$Conservateur, antifongique et insecticide léger à faible dose.$$, $$Danger modéré, toxique à forte dose — tenir hors de portée des enfants.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide tartrique$$, $$Acide de fermentation utilisé en agroalimentaire (vin) et en cosmétique pour ajuster le pH.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide benzoique$$, $$Conservateur antimicrobien, base du benzoate de sodium.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide gluconique$$, $$Séquestrant doux, anticalcaire alternatif à l'EDTA dans les formules plus douces.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Sel de Glauber$$, $$Sulfate de sodium décahydraté, régulateur de pH pour usage industriel.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Chlorure de calcium$$, $$Sel utilisé pour le traitement de l'eau, l'antigel et comme dessiccant.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Sulfate d'aluminium (Alun)$$, $$Floculant utilisé dans le traitement de l'eau pour clarifier en agrégeant les particules en suspension.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Parfums de synthese$$, $$Compositions aromatiques synthétiques utilisées pour parfumer détergents, savons et cires.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Huiles essentielles$$, $$Extraits aromatiques naturels de plantes, utilisés en cosmétique et savonnerie naturelle.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Fixateurs de parfum$$, $$Additifs qui ralentissent l'évaporation du parfum pour prolonger sa tenue sur le produit.$$, null),
  ($$matieres-premieres$$, $$Colorants$$, $$Colorants cosmetiques$$, $$Colorants approuvés pour un usage cosmétique.$$, null),
  ($$matieres-premieres$$, $$Colorants$$, $$Colorants industriels$$, $$Colorants utilisés pour teinter détergents et savons industriels.$$, null),
  ($$matieres-premieres$$, $$Colorants$$, $$Pigments (oxydes de fer, TiO2)$$, $$Pigments minéraux utilisés pour la coloration de la peinture.$$, null),
  ($$matieres-premieres$$, $$Huiles & Beurres Cosmétiques$$, $$Paraffine$$, $$Cire minérale dérivée du pétrole, base de nombreuses cires industrielles.$$, null),
  ($$matieres-premieres$$, $$Huiles & Beurres Cosmétiques$$, $$Cire d'abeille$$, $$Cire naturelle produite par les abeilles, utilisée en cosmétique pour texturer baumes et bougies.$$, null),
  ($$matieres-premieres$$, $$Huiles & Beurres Cosmétiques$$, $$Cire de carnauba$$, $$Cire végétale très dure, apporte brillance et dureté (cires voiture, meubles).$$, null),
  ($$matieres-premieres$$, $$Huiles & Beurres Cosmétiques$$, $$Beurre de karite$$, $$Beurre végétal nourrissant, très utilisé en cosmétique et soins du corps.$$, null),
  ($$matieres-premieres$$, $$Huiles & Beurres Cosmétiques$$, $$Beurre de cacao$$, $$Beurre végétal riche, utilisé en cosmétique pour ses propriétés nourrissantes et son parfum naturel.$$, null),
  ($$matieres-premieres$$, $$Huiles & Beurres Cosmétiques$$, $$Huile de coco/palme$$, $$Huiles végétales saponifiables, base de fabrication de savons et cires.$$, null),
  ($$anti-nuisibles$$, $$Insecticides Maison$$, $$Permethrine (concentre)$$, $$Insecticide de synthèse (pyréthrinoïde) à action de contact, base des insecticides maison.$$, $$Toxique pour les organismes aquatiques — ne jamais rejeter dans les eaux.$$),
  ($$anti-nuisibles$$, $$Insecticides Extérieur$$, $$Deltamethrine (concentre)$$, $$Insecticide pyréthrinoïde puissant à action rapide, utilisé en traitement extérieur.$$, $$Toxique — respecter les doses d'usage, éviter le contact avec la peau.$$),
  ($$anti-nuisibles$$, $$Anti-Fourmis & Cafards$$, $$Cypermethrine (concentre)$$, $$Insecticide pyréthrinoïde à effet résiduel prolongé, efficace contre fourmis et cafards.$$, $$Toxique — usage en zone ventilée.$$),
  ($$anti-nuisibles$$, $$Anti-Fourmis & Cafards$$, $$Fipronil (concentre)$$, $$Insecticide à action lente utilisé en appâts gel (effet domino sur la colonie).$$, $$Toxique, usage encadré — tenir hors de portée des enfants et animaux.$$),
  ($$anti-nuisibles$$, $$Raticides & Rongeurs$$, $$Bromadiolone (concentre)$$, $$Anticoagulant puissant utilisé comme raticide professionnel.$$, $$Très toxique, réglementé — usage réservé aux professionnels formés, risque pour la faune non-cible.$$),
  ($$anti-nuisibles$$, $$Insecticides Maison$$, $$Piperonyl butoxide (PBO)$$, $$Synergiste qui renforce l'efficacité des insecticides pyréthrinoïdes sans être lui-même insecticide.$$, $$Danger modéré.$$),
  ($$anti-nuisibles$$, $$Anti-Moustiques & Mouches$$, $$DEET (concentre)$$, $$Répulsif corporel de référence contre moustiques et insectes piqueurs.$$, $$Danger modéré — respecter les concentrations d'usage cutané.$$),
  ($$matieres-premieres$$, $$Désinfectants$$, $$TCCA (Trichloroisocyanurate)$$, $$Chlore stabilisé sous forme solide, utilisé pour la désinfection de l'eau de piscine.$$, $$Oxydant — ne jamais mélanger avec d'autres produits chimiques.$$),
  ($$anti-nuisibles$$, $$Produits Agrivet$$, $$Sulfate de cuivre$$, $$Algicide utilisé pour le traitement de bassins et plans d'eau.$$, $$Toxique pour la vie aquatique à forte dose.$$),
  ($$matieres-premieres$$, $$Polymères & Résines$$, $$Polymeres floculants$$, $$Polymères de synthèse qui agrègent les particules en suspension pour clarifier l'eau.$$, null),
  ($$matieres-premieres$$, $$Charges Minérales$$, $$Charbon actif (vrac)$$, $$Charbon à très grande surface d'adsorption, utilisé pour la filtration et la purification de l'eau/air.$$, null),
  ($$matieres-premieres$$, $$Charges Minérales$$, $$Ceramique filtrante (vrac)$$, $$Support de filtration minéral poreux, utilisé dans les systèmes de filtration d'eau.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Saccharose (Sucre blanc raffiné / Sucre SP)$$, $$Sucre de table de référence, édulcorant de base et substrat de fermentation en agroalimentaire.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Glucose / Dextrose monohydraté$$, $$Sucre simple directement fermentescible, utilisé comme anticristallisant et substrat pour levures.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Fructose (Lévulose)$$, $$Sucre naturel à pouvoir sucrant élevé, utilisé comme édulcorant et anticristallisant.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Sirop de glucose-fructose (HFCS)$$, $$Édulcorant liquide industriel à base d'amidon de maïs, stabilise texture et douceur des boissons.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Stévia (Glycosides de stéviol E960)$$, $$Édulcorant naturel extrait de la plante Stevia, zéro calorie, pouvoir sucrant très élevé.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Aspartame (E951)$$, $$Édulcorant intense artificiel utilisé dans les boissons 'light'.$$, $$Déconseillé aux personnes phénylcétonuriques (contient de la phénylalanine).$$),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Acésulfame de potassium (Ace-K / E950)$$, $$Édulcorant intense sans calories, stable à la chaleur, souvent combiné à d'autres édulcorants.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Sucralose (E955)$$, $$Édulcorant intense (environ 600 fois le sucre), stable à la chaleur et au pH, dérivé du sucre.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Saccharine sodique (E954)$$, $$Édulcorant intense artificiel historique, utilisé dans les boissons et produits diététiques.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Sorbitol (E420)$$, $$Polyol utilisé comme édulcorant, humectant et anticristallisant.$$, $$Effet laxatif à forte dose.$$),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Maltodextrine$$, $$Agent de charge glucidique neutre, utilisé comme support d'arômes lors du séchage par atomisation.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide citrique monohydraté (E330)$$, $$Acidifiant universel, antioxydant et séquestrant de métaux en agroalimentaire.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide tartrique L(+) (E334)$$, $$Acidifiant du vin, utilisé aussi comme levant chimique combiné au bicarbonate.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide citrique anhydre (E330)$$, $$Version anhydre de l'acide citrique, plus concentrée et moins hygroscopique.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide malique DL (E296)$$, $$Acidifiant à note fruitée (pomme-poire), utilisé en vinification et confiserie.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide phosphorique H₃PO₄ (E338)$$, $$Acidifiant signature des colas, corrige aussi le pH de l'eau de brassage.$$, $$Corrosif à l'état concentré.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide acétique / Vinaigre blanc (E260)$$, $$Acide de conservation par acidification, arôme vinaigrette.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Carbonate de calcium CaCO₃ (E170)$$, $$Désacidifiant et antiagglomérant, source de calcium alimentaire.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Bicarbonate de sodium NaHCO₃ (E500ii)$$, $$Agent levant et régulateur de pH doux.$$, null),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Métabisulfite de potassium (E224) — 'Meta K'$$, $$Antiseptique et antioxydant majeur en vinification et jus de fruits.$$, $$Allergène (sulfites) — étiquetage obligatoire.$$),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Acide ascorbique / Ascorbate Na (E300/E301)$$, $$Antioxydant universel, fixateur de couleur et acidifiant doux.$$, null),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Acide sorbique (E200)$$, $$Forme acide du sorbate, conservateur antifongique naturel.$$, null),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Nitrite de sodium / Sel nitrité (E250)$$, $$Conservateur de charcuterie, fixe la couleur rose et prévient le botulisme.$$, $$Usage strictement dosé — toxique à haute concentration, réglementé en charcuterie.$$),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Salpêtre / Nitrate de potassium (E252)$$, $$Conservateur traditionnel de charcuterie sèche à maturation lente.$$, $$Usage réglementé.$$),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Lysozyme (E1105)$$, $$Enzyme antibactérienne naturelle (blanc d'œuf), inhibe les bactéries lactiques du vin et conserve le fromage.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Gélatine alimentaire en poudre (200 Bloom)$$, $$Gélifiant animal thermoréversible, utilisé pour la texture et la clarification.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Agar-Agar (E406)$$, $$Gélifiant végétal extrait d'algues rouges, forme un gel ferme et thermostable.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Carraghénanes (E407)$$, $$Épaississant d'algues rouges, stabilise notamment les produits laitiers.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Pectine HM (E440i)$$, $$Gélifiant naturel de fruits, nécessite une forte teneur en sucre pour gélifier.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Gomme arabique (E414)$$, $$Stabilisant d'émulsion pour arômes, aussi utilisée pour le collage du vin.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Gomme guar (E412)$$, $$Épaississant économique, stabilise glaces et sauces.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$CMC / Carboxyméthylcellulose (E466) — Tylose$$, $$Liant de pâte à sucre et stabilisant de vin, anti-cristallisant des glaces.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Glycérine / Glycérol alimentaire (E422)$$, $$Humectant alimentaire, apporte du corps en bouche et retient l'humidité.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Amidon natif (maïs, tapioca, pomme de terre)$$, $$Épaississant et liant de base non modifié.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Amidon modifié (E1400–E1452)$$, $$Amidon traité pour résister à la chaleur, aux acides et à la congélation-décongélation.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Lécithine de soja (E322)$$, $$Émulsifiant universel d'origine végétale, agent de surface et dispersant.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Mono- et diglycérides d'acides gras (E471)$$, $$Émulsifiant qui stabilise l'aération et la texture grasse des produits.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Tripolyphosphate de sodium STPP (E451)$$, $$Agent de rétention d'eau, texture la viande et aide à l'émulsification du fromage fondu.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Plasmal (mélange phosphates alimentaires)$$, $$Mélange de phosphates pour rétention d'eau et texture des produits carnés.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Polysorbate 80 (E433)$$, $$Émulsifiant synthétique, stabilise les glaces et solubilise les arômes.$$, null),
  ($$matieres-premieres$$, $$Colorants$$, $$Caramel alimentaire (E150a — classe I)$$, $$Colorant brun de cuisson, standardise aussi le goût.$$, null),
  ($$matieres-premieres$$, $$Colorants$$, $$Colorant rouge ponceau 4R (E124)$$, $$Colorant rouge vif de synthèse, utilisé en confiserie et sodas.$$, $$Allergène potentiel — étiquetage obligatoire.$$),
  ($$matieres-premieres$$, $$Colorants$$, $$Colorant rouge vin / anthocyanes (E163)$$, $$Colorant naturel rouge-violet extrait de raisin/fruits rouges.$$, null),
  ($$matieres-premieres$$, $$Colorants$$, $$Tartrazine jaune citron (E102)$$, $$Colorant jaune vif de synthèse.$$, $$Allergène potentiel — étiquetage obligatoire.$$),
  ($$matieres-premieres$$, $$Colorants$$, $$Bleu brillant FCF (E133)$$, $$Colorant bleu vif, combiné au E102 pour obtenir un vert.$$, null),
  ($$matieres-premieres$$, $$Colorants$$, $$Jaune orangé S (E110)$$, $$Colorant orange de synthèse.$$, $$Allergène potentiel — étiquetage obligatoire.$$),
  ($$matieres-premieres$$, $$Colorants$$, $$Dioxyde de titane (E171)$$, $$Colorant blanc opacifiant, apporte brillance aux glaçages.$$, $$Usage alimentaire restreint dans certaines juridictions — vérifier la réglementation en vigueur.$$),
  ($$matieres-premieres$$, $$Colorants$$, $$Bétacarotène (E160a)$$, $$Colorant naturel orange-jaune, précurseur de vitamine A.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Dioxyde de carbone CO₂ alimentaire$$, $$Gaz utilisé pour la carbonatation des sodas, eaux gazeuses et bières.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Caféine (anhydre)$$, $$Stimulant naturel, exhausteur d'amertume signature des boissons énergisantes.$$, $$Dosage réglementé dans les boissons — respecter les limites légales.$$),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Taurine$$, $$Acide aminé utilisé dans les boissons énergisantes, antioxydant endogène.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Inositol / Myo-inositol (Vitamine B8)$$, $$Cofacteur métabolique ajouté aux boissons fonctionnelles.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Vitamines B3, B6, B12 (niacine, pyridoxine, cobalamine)$$, $$Vitamines d'enrichissement nutritionnel des boissons fonctionnelles et énergisantes.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Arôme naturel de fruits (concentré)$$, $$Concentré aromatique naturel pour parfumage et correction de goût.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Chlorure de calcium CaCl₂ alimentaire$$, $$Affermit le caillé du fromage et raffermit les légumes en conserve.$$, null),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Sel nitrité (0.6% NaNO₂ dans NaCl)$$, $$Mélange prêt à l'emploi pour salaison, sécurité et couleur de la charcuterie.$$, $$Usage réglementé — respecter le taux de nitrite légal.$$),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Salpêtre (Nitrate de potassium KNO₃ E252)$$, $$Conservation longue durée pour jambon sec et saucissons à maturation.$$, $$Usage réglementé.$$),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Ascorbate de sodium (E301)$$, $$Fixateur de couleur de charcuterie, accélère la salaison et protège de l'oxydation.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Levure chimique (poudre à lever)$$, $$Agent levant chimique pour pâtisserie, développe la texture aérée des gâteaux.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Crème de tartre (Tartrate acide de potassium E336)$$, $$Stabilisant des blancs en neige, acide pour levain chimique, régulateur de pH en meringue.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Tylose CMC (Pâtisserie décorative)$$, $$Durcissant de pâte à sucre pour modelage et fleurs décoratives.$$, null),
  ($$matieres-premieres$$, $$Huiles & Beurres Cosmétiques$$, $$Glycérine pure alimentaire (E422)$$, $$Humectant plastifiant qui garde la pâte à sucre souple plus longtemps.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Soude caustique NaOH (grade alimentaire)$$, $$Nettoyage alcalin CIP (Clean-in-Place) et dégraissage des lignes de production.$$, $$Corrosif fort.$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide phosphorique H₃PO₄ alimentaire (E338)$$, $$Détartrage acide CIP, dissout les dépôts calcaires des circuits.$$, $$Corrosif modéré.$$),
  ($$matieres-premieres$$, $$Désinfectants$$, $$Acide peracétique (PAA)$$, $$Désinfectant puissant à froid, bactéricide, fongicide et virucide à large spectre.$$, $$Corrosif — vapeurs irritantes, manipuler sous ventilation.$$),
  ($$matieres-premieres$$, $$Désinfectants$$, $$Hypochlorite de sodium NaClO (eau de Javel)$$, $$Désinfectant chloré de l'eau de process et des surfaces.$$, $$Corrosif, oxydant — jamais mélangé à un acide (dégagement de chlore gazeux toxique).$$),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide nitrique dilué HNO₃ (nettoyage inox)$$, $$Détartrage de l'inox, dissout les dépôts minéraux tenaces.$$, $$Corrosif fort.$$),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Extrait de vanille naturel (Bourbon)$$, $$Arôme premium à note crémeuse-boisée, extrait de gousses de vanille.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Vanilline de synthèse (éthylvanilline)$$, $$Arôme vanille économique de synthèse, dosage précis et reproductible.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Glutamate monosodique MSG (E621)$$, $$Exhausteur de goût umami, amplifie les saveurs salées.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Caféine anhydre$$, $$Stimulant naturel, amertume signature des energy drinks.$$, $$Dosage réglementé dans les boissons — respecter les limites légales.$$),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Acide citrique + Sorbate K — combo conservateur standard$$, $$Association classique acidifiant + conservateur, protection complète pH-dépendante et économique.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Épices alimentaires (cannelle, muscade, gingembre, clou de girofle)$$, $$Épices naturelles à propriétés aromatiques et antimicrobiennes légères.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Houblon — pellets T90 et extrait CO₂$$, $$Apporte amertume, arôme et conservation naturelle à la bière.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Extrait de malt liquide / poudre$$, $$Base sucrée et aromatique, constitue le corps de la bière.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Pectine HM rapide (Extra-Rapide/Rapide)$$, $$Gélifiant à prise rapide pour confitures riches en sucre.$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$Pectine LM (Faible méthylation) / Amidée$$, $$Gélifiant pour confitures allégées en sucre et produits laitiers.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Chlorure de calcium CaCl₂ (texturation conserves)$$, $$Raffermit les légumes en conserve en activant la pectine naturelle.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Vinaigre blanc / Acide acétique (acidification conserves)$$, $$Conservation par acidification pour cornichons et pickles.$$, null),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Benzoate de sodium + Sorbate de K (combo conserves)$$, $$Conservation élargie anti-moisissures et antibactérienne.$$, null),
  ($$matieres-premieres$$, $$Chélatants$$, $$EDTA disodique (E385)$$, $$Séquestrant de métaux, stabilise couleur et saveur des conserves.$$, null),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Sulfite de sodium / Métabisulfite de sodium (E221/E223)$$, $$Antioxydant et agent de blanchiment, anti-brunissement des fruits secs.$$, $$Allergène (sulfites) — étiquetage obligatoire.$$),
  ($$matieres-premieres$$, $$Épaississants$$, $$Stabilisateur glace (combo gommes)$$, $$Mélange de gommes anti-cristallisation pour une texture crémeuse et une bonne tenue à la fonte.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Saccharose inverti (Trimoline)$$, $$Abaisse le point de congélation, garde une texture souple à froid.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Dextrose (glucose anhydre pour glaces)$$, $$Abaisse le point de congélation, anticristallisant de texture.$$, null),
  ($$matieres-premieres$$, $$Parfums & Additifs$$, $$Sirop de glucose (DE 38–42)$$, $$Anticristallisant, épaississant, apporte du corps et une bonne tenue à la fonte.$$, null),
  ($$matieres-premieres$$, $$Charges Minérales$$, $$Bentonite œnologique (clarification vin)$$, $$Argile utilisée pour clarifier et stabiliser thermiquement le vin (collage).$$, null),
  ($$matieres-premieres$$, $$Épaississants$$, $$CMC alimentaire (stabilisation tartrique vin)$$, $$Inhibe la cristallisation du tartrate, alternative à la réfrigération du vin.$$, null),
  ($$matieres-premieres$$, $$Charges Minérales$$, $$Diatomite / Kieselguhr (filtration)$$, $$Roche siliceuse utilisée pour la filtration fine avant mise en bouteille.$$, null),
  ($$matieres-premieres$$, $$Charges Minérales$$, $$Charbon actif œnologique (décoloration)$$, $$Décolore et déodorise, élimine l'excès de tanins du vin.$$, null),
  ($$matieres-premieres$$, $$Colorants$$, $$Colorant caramel ammoniacal-sulfite (Classe IV — E150d)$$, $$Colorant brun-noir puissant, seul autorisé pour les colas et sodas acides au H₃PO₄.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Citrate de sodium / Citrate de potassium (E331/E332)$$, $$Régulateur d'acidité et séquestrant, stabilise le goût acide des boissons gazeuses.$$, null),
  ($$matieres-premieres$$, $$Acides & Bases$$, $$Acide fumarique (E297)$$, $$Acidifiant économique, alternative à l'acide citrique/tartrique pour poudres à diluer.$$, null),
  ($$matieres-premieres$$, $$Conservateurs & Antioxydants$$, $$Nisine (E234)$$, $$Conservateur biologique à large spectre contre les bactéries Gram+ (Listeria, Clostridium botulinum).$$, null),
  ($$matieres-premieres$$, $$Charges Minérales$$, $$Silice colloïdale / Dioxyde de silicium (E551)$$, $$Anti-agglomérant, améliore l'écoulement des poudres et sirops en sachet.$$, null),
  ($$matieres-premieres$$, $$Désinfectants$$, $$Peroxyde d'hydrogène alimentaire (H₂O₂) — grade stérilisation emballage$$, $$Stérilise les emballages aseptiques (type Tetra Pak/gourdes) avant remplissage à froid.$$, $$Oxydant — manipuler avec gants et protection oculaire.$$),
  ($$matieres-premieres$$, $$Charges Minérales$$, $$Sel de table / Chlorure de sodium alimentaire (NaCl)$$, $$Exhausteur de goût traditionnel et régulateur osmotique.$$, null)
) as v(business_unit_slug, category_name, name, description, safety_note)
join public.business_units bu on bu.slug = v.business_unit_slug
on conflict (business_unit_id, category_name, name) do nothing;
