-- ============================================================
-- AkoraHub - Patch Phase 231 : journal des consultations de fiche
-- produit sur le site web
--
-- Contexte (08/09) : demande explicite — savoir quelles fiches produit
-- attirent le plus de visites sur le site, sans commande derrière (utile
-- pour ajuster prix/stock/mise en avant).
--
-- Une ligne par produit consulté et par session (sessionStorage côté
-- produit.html, logProductView) — pas à chaque rechargement de la page.
-- product_name dupliqué ici volontairement (dénormalisé) : le rapport
-- doit rester lisible même si le produit est renommé ou supprimé plus
-- tard.
--
-- Insertion directe depuis le navigateur (comme catalogue_searches,
-- phase230) — RLS insert-only pour anon/authenticated, lecture réservée
-- à l'admin.
--
-- À exécuter une seule fois : Supabase Dashboard -> SQL Editor -> New
-- query. Idempotent (create if not exists).
-- ============================================================

create table if not exists public.product_views (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  product_id uuid,
  product_name text,
  session_id text
);

create index if not exists product_views_created_at_idx on public.product_views (created_at);
create index if not exists product_views_product_id_idx on public.product_views (product_id);

alter table public.product_views enable row level security;

drop policy if exists "product_views_insert_all" on public.product_views;
create policy "product_views_insert_all" on public.product_views
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "product_views_select_admin" on public.product_views;
create policy "product_views_select_admin" on public.product_views
  for select
  to authenticated
  using (public.current_role_is_admin());

-- Vérification : la table existe, RLS active, 2 policies (insert + select admin).
select policyname, cmd, roles from pg_policies where tablename = 'product_views';
