-- ============================================================
-- AkoraHub - Patch Phase 226 : journal détaillé des visites du site web
--
-- Contexte (08/09) : le badge public "X visites" (phase221,
-- site_visit_counter) ne garde qu'un total global, sans détail par pays,
-- par page ou dans le temps — insuffisant pour un vrai rapport de
-- fréquentation. Cloudflare Web Analytics devrait normalement fournir ce
-- détail, mais son script (cloudflareinsights.com) est bloqué chez une
-- partie significative des visiteurs (bloqueurs de pub/vie privée), donc
-- peu fiable comme seule source. Cette table est alimentée côté serveur
-- par functions/track-visit.js (dépôt groupe-akora-site, Cloudflare Pages
-- Function) — le pays vient de request.cf.country (Cloudflare lui-même),
-- jamais d'un script tiers bloquable.
--
-- Une ligne par visite (une par session de navigation, même logique que
-- site_visit_counter — voir site/assets/visits.js), pas par page vue.
--
-- Lecture réservée au SQL Editor du dashboard Supabase (connecté en tant
-- que propriétaire du projet, qui contourne RLS) — aucune policy SELECT
-- pour anon/authenticated, ces données ne sont jamais exposées via l'API
-- REST publique. Seul l'INSERT est ouvert, sans authentification (comme
-- site_visit_counter), pour que la Function Cloudflare puisse écrire sans
-- clé privilégiée.
--
-- À exécuter une seule fois : Supabase Dashboard -> SQL Editor -> New
-- query. Idempotent (create if not exists).
-- ============================================================

create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  path text,
  referrer text,
  country text,
  session_id text
);

create index if not exists site_visits_created_at_idx on public.site_visits (created_at);
create index if not exists site_visits_country_idx on public.site_visits (country);

alter table public.site_visits enable row level security;

drop policy if exists "site_visits_insert_all" on public.site_visits;
create policy "site_visits_insert_all" on public.site_visits
  for insert
  to anon, authenticated
  with check (true);

-- Vérification : la table existe, RLS est active, une seule policy (INSERT).
select relrowsecurity from pg_class where relname = 'site_visits';
select policyname, cmd from pg_policies where tablename = 'site_visits';
