-- ============================================================
-- AkoraHub - Patch Phase 33 : Suggestions de noms pour Matières Premières
-- À exécuter une seule fois : Supabase Dashboard -> SQL Editor -> New query
--
-- Liste de noms de matières premières (chimiques + ingrédients
-- alimentaires) à choisir dans un sélecteur au moment d'ajouter un
-- produit (lib/presentation/product_management_real/), plutôt que de
-- tout taper à la main. Organisée par pilier + catégorie existants
-- (voir phase10_patch_new_business_units.sql) : Matières Premières (12
-- catégories), Matières Premières Peinture, Anti-Nuisibles. Les
-- ingrédients alimentaires vont dans leur famille chimique avec une note
-- "qualité alimentaire" (convention déjà actée avec l'utilisateur, voir
-- phase10). Rien n'est retiré/désactivé : juste des suggestions, le nom
-- reste librement modifiable au moment de créer le produit.
--
-- Relecture avant exécution (demandée par l'utilisateur) : 11 doublons
-- retirés — même substance listée deux fois (une fois nom simple, une
-- fois variante E-number/cas d'usage), ou carrément le même nom exact
-- rangé dans deux catégories différentes (Sulfate de sodium, STPP,
-- Sulfate d'aluminium).
-- ============================================================

create table if not exists public.raw_material_name_suggestions (
  id uuid primary key default gen_random_uuid(),
  business_unit_slug text not null,
  category_name text not null,
  name text not null,
  note text,
  created_at timestamptz not null default now(),
  unique (business_unit_slug, category_name, name)
);

alter table public.raw_material_name_suggestions enable row level security;

drop policy if exists "raw_material_name_suggestions_staff_only" on public.raw_material_name_suggestions;
create policy "raw_material_name_suggestions_staff_only" on public.raw_material_name_suggestions
  for select using (public.current_role_is_staff());

drop policy if exists "raw_material_name_suggestions_write_admin_only" on public.raw_material_name_suggestions;
create policy "raw_material_name_suggestions_write_admin_only" on public.raw_material_name_suggestions
  for all using (public.current_role_is_admin())
  with check (public.current_role_is_admin());

insert into public.raw_material_name_suggestions (business_unit_slug, category_name, name, note) values
  ('matieres-premieres', 'Tensioactifs', 'LABSA (Acide Sulfonique Lineaire)', 'Agent tensioactif principal | Dosage conseille: 10-20% | Danger: Corrosif'),
  ('matieres-premieres', 'Épaississants', 'CMC', 'Epaississant, stabilisant | Dosage conseille: 0.5-2%'),
  ('matieres-premieres', 'Charges Minérales', 'Sulfate de sodium', 'Charge, texture poudre | Dosage conseille: 5-15%'),
  ('matieres-premieres', 'Acides & Bases', 'Bicarbonate de soude', 'Abrasif doux, desodorisant'),
  ('matieres-premieres', 'Désinfectants', 'Hypochlorite de calcium 70%', 'Base eau de javel | Danger: Oxydant, corrosif'),
  ('matieres-premieres', 'Tensioactifs', 'Comperlan / Cocamide DEA', 'Agent moussant | Dosage conseille: 1-5%'),
  ('matieres-premieres', 'Chélatants', 'EDTA / Sequestrant', 'Anti-calcaire, stabilisation | Dosage conseille: 0.1-1%'),
  ('matieres-premieres', 'Huiles & Beurres Cosmétiques', 'Glycerine technique', 'Adoucissant, hydratant savon | Dosage conseille: 1-5%'),
  ('matieres-premieres', 'Huiles & Beurres Cosmétiques', 'Huile de coco', 'Base saponification'),
  ('matieres-premieres', 'Tensioactifs', 'SLS', 'Nettoyant fort, mousse | Dosage conseille: 1-10% | Danger: Irritant possible'),
  ('matieres-premieres', 'Tensioactifs', 'SLES', 'Shampooing, gel douche, menage | Dosage conseille: 1-15%'),
  ('matieres-premieres', 'Tensioactifs', 'LAS', 'Detergent menager | Dosage conseille: 5-30%'),
  ('matieres-premieres', 'Tensioactifs', 'AOS', 'Nettoyant puissant | Dosage conseille: 5-40%'),
  ('matieres-premieres', 'Tensioactifs', 'SLSA', 'Mousse, poudre lavante | Dosage conseille: 1-30%'),
  ('matieres-premieres', 'Tensioactifs', 'Sodium Coco-Sulfate', 'Solide, shampoing | Dosage conseille: 3-20%'),
  ('matieres-premieres', 'Tensioactifs', 'CAPB', 'Douceur, mousse | Dosage conseille: 1-20%'),
  ('matieres-premieres', 'Tensioactifs', 'Cocamidopropyl Hydroxysultaine', 'Stabilisateur mousse | Dosage conseille: 1-10%'),
  ('matieres-premieres', 'Tensioactifs', 'Decyl Glucoside', 'Nettoyant doux | Dosage conseille: 1-20%'),
  ('matieres-premieres', 'Tensioactifs', 'Coco Glucoside', 'Shampooing, gel douche | Dosage conseille: 1-15%'),
  ('matieres-premieres', 'Tensioactifs', 'Lauryl Glucoside', 'Nettoyant doux | Dosage conseille: 1-10%'),
  ('matieres-premieres', 'Tensioactifs', 'Sodium Lauroyl Sarcosinate', 'Nettoyant doux, dentifrice'),
  ('matieres-premieres', 'Acides & Bases', 'Acide citrique alimentaire', 'Conservateur, acidifiant'),
  ('matieres-premieres', 'Acides & Bases', 'Bicarbonate de soude alimentaire', 'Levant, correcteur acidite'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Benzoate de sodium', 'Conservateur'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Sorbate de potassium', 'Conservateur anti-moisissure'),
  ('matieres-premieres', 'Charges Minérales', 'Sel alimentaire raffine', 'Conservation, gout'),
  ('matieres-premieres', 'Colorants', 'Colorants alimentaires certifies', 'Couleur produit'),
  ('matieres-premieres', 'Parfums & Additifs', 'Aromes alimentaires', 'Gout'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Acide ascorbique (Vitamine C)', 'Antioxydant alimentaire'),
  ('matieres-premieres', 'Épaississants', 'Pectine', 'Gelifiant (confitures, sirops)'),
  ('matieres-premieres', 'Épaississants', 'Gomme xanthane', 'Epaississant alimentaire'),
  ('matieres-premieres-peinture', 'Liants & Résines', 'Resines acryliques/vinyliques', 'Liant peinture'),
  ('matieres-premieres-peinture', 'Pigments & Colorants', 'Pigments (oxydes de fer, TiO2)', 'Couleur, opacite'),
  ('matieres-premieres-peinture', 'Solvants & Diluants', 'Solvants (White spirit, xylene)', 'Dilution, nettoyage | Danger: Inflammable'),
  ('matieres-premieres-peinture', 'Siccatifs & Conservateurs', 'Siccatifs (cobalt, manganese)', 'Accelerateur de sechage | Danger: Toxique a dose'),
  ('matieres-premieres-peinture', 'Charges & Additifs', 'Charges minerales (carbonate calcium, talc)', 'Texture, opacite, cout'),
  ('matieres-premieres-peinture', 'Charges & Additifs', 'Dispersants/Agents mouillants', 'Stabilite pigment'),
  ('matieres-premieres-peinture', 'Charges & Additifs', 'Epaississants cellulosiques', 'Viscosite peinture'),
  ('matieres-premieres-peinture', 'Charges & Additifs', 'Anti-mousse', 'Eviter bulles a l''application'),
  ('matieres-premieres-peinture', 'Siccatifs & Conservateurs', 'Conservateurs (biocides peinture)', 'Anti-moisissure en pot'),
  ('matieres-premieres-peinture', 'Pigments & Colorants', 'Encre de base (colorants concentres)', 'Fabrication encre'),
  ('matieres-premieres', 'Solvants', 'Ethanol (alcool ethylique)', 'Gel hydroalcoolique, parfums, desinfection | Danger: Inflammable'),
  ('matieres-premieres', 'Solvants', 'Alcool isopropylique (IPA)', 'Desinfectant surfaces, nettoyage electronique | Danger: Inflammable'),
  ('matieres-premieres', 'Solvants', 'Methanol', 'Solvant industriel, antigel, encres | Danger: Toxique - tres dangereux'),
  ('matieres-premieres', 'Solvants', 'Alcool benzylique', 'Conservateur cosmetique, solvant parfum | Danger: Modere'),
  ('matieres-premieres', 'Solvants', 'Alcool cetylique', 'Epaississant/texture | Danger: Faible'),
  ('matieres-premieres', 'Solvants', 'Propylene glycol', 'Solvant, humectant, antigel | Danger: Faible-modere'),
  ('matieres-premieres', 'Solvants', 'Alcool denature', 'Nettoyage industriel, dilution vernis | Danger: Inflammable'),
  ('matieres-premieres', 'Acides & Bases', 'Soude caustique', 'Saponification, neutralisation, debouchage | Danger: Corrosif fort'),
  ('matieres-premieres', 'Acides & Bases', 'Potasse caustique', 'Savon liquide/mou, cosmetique | Danger: Corrosif fort'),
  ('matieres-premieres', 'Acides & Bases', 'Carbonate de sodium', 'Adoucissant d''eau, base javel, degraissant | Danger: Modere'),
  ('matieres-premieres', 'Acides & Bases', 'Ammoniaque', 'Degraissant puissant, nettoyant vitres | Danger: Corrosif, vapeurs irritantes'),
  ('matieres-premieres', 'Acides & Bases', 'Metasilicate de sodium', 'Degraissant industriel, anticorrosion | Danger: Corrosif'),
  ('matieres-premieres', 'Acides & Bases', 'Silicate de sodium', 'Detergent, anti-redeposition | Danger: Modere'),
  ('matieres-premieres', 'Acides & Bases', 'Chaux eteinte', 'Traitement de l''eau, correction pH | Danger: Modere'),
  ('matieres-premieres', 'Acides & Bases', 'Acide chlorhydrique', 'Detartrant puissant, ajustement pH piscine | Danger: Corrosif fort'),
  ('matieres-premieres', 'Acides & Bases', 'Acide sulfurique', 'Detartrant industriel, batteries, pH | Danger: Tres dangereux'),
  ('matieres-premieres', 'Acides & Bases', 'Acide phosphorique', 'Detartrant, antirouille, additif alimentaire | Danger: Corrosif modere'),
  ('matieres-premieres', 'Acides & Bases', 'Acide nitrique', 'Nettoyage metaux, passivation inox | Danger: Corrosif fort, oxydant'),
  ('matieres-premieres', 'Acides & Bases', 'Acide sulfamique', 'Detartrant solide, sur d''usage | Danger: Modere'),
  ('matieres-premieres', 'Acides & Bases', 'Acide citrique', 'Detartrant doux, conservateur, cosmetique | Danger: Faible'),
  ('matieres-premieres', 'Acides & Bases', 'Acide acetique', 'Detartrant ecologique, neutralisant | Danger: Modere concentre'),
  ('matieres-premieres', 'Acides & Bases', 'Acide lactique', 'Cosmetique (exfoliant), conservateur | Danger: Faible'),
  ('matieres-premieres', 'Acides & Bases', 'Acide oxalique', 'Detachant rouille, blanchiment bois | Danger: Toxique, usage encadre'),
  ('matieres-premieres', 'Acides & Bases', 'Acide borique', 'Conservateur, antifongique, insecticide leger | Danger: Modere, toxique a forte dose'),
  ('matieres-premieres', 'Acides & Bases', 'Acide tartrique', 'Agroalimentaire, cosmetique (pH) | Danger: Faible'),
  ('matieres-premieres', 'Acides & Bases', 'Acide benzoique', 'Conservateur (base benzoate) | Danger: Faible'),
  ('matieres-premieres', 'Acides & Bases', 'Acide gluconique', 'Sequestrant, anticalcaire doux | Danger: Faible'),
  ('matieres-premieres', 'Acides & Bases', 'Sel de Glauber', 'Regulateur pH industriel'),
  ('matieres-premieres', 'Acides & Bases', 'Chlorure de calcium', 'Traitement eau, antigel, dessiccant'),
  ('matieres-premieres', 'Acides & Bases', 'Sulfate d''aluminium (Alun)', 'Floculant traitement de l''eau'),
  ('matieres-premieres', 'Parfums & Additifs', 'Parfums de synthese', 'Detergents, savons, cire'),
  ('matieres-premieres', 'Parfums & Additifs', 'Huiles essentielles', 'Cosmetique, savons naturels'),
  ('matieres-premieres', 'Parfums & Additifs', 'Fixateurs de parfum', 'Stabilisation odeur longue duree'),
  ('matieres-premieres', 'Colorants', 'Colorants cosmetiques', 'Cosmetique'),
  ('matieres-premieres', 'Colorants', 'Colorants industriels', 'Detergents, savons'),
  ('matieres-premieres', 'Colorants', 'Pigments (oxydes de fer, TiO2)', 'Peinture'),
  ('matieres-premieres', 'Huiles & Beurres Cosmétiques', 'Paraffine', 'Base cire industrielle'),
  ('matieres-premieres', 'Huiles & Beurres Cosmétiques', 'Cire d''abeille', 'Cire naturelle, cosmetique'),
  ('matieres-premieres', 'Huiles & Beurres Cosmétiques', 'Cire de carnauba', 'Brillance, durete (voiture, meubles)'),
  ('matieres-premieres', 'Huiles & Beurres Cosmétiques', 'Beurre de karite', 'Cosmetique, cire soin'),
  ('matieres-premieres', 'Huiles & Beurres Cosmétiques', 'Beurre de cacao', 'Cosmetique'),
  ('matieres-premieres', 'Huiles & Beurres Cosmétiques', 'Huile de coco/palme', 'Base savon, cire'),
  ('anti-nuisibles', 'Insecticides Maison', 'Permethrine (concentre)', 'Base insecticide contact | Danger: Toxique aquatique'),
  ('anti-nuisibles', 'Insecticides Extérieur', 'Deltamethrine (concentre)', 'Base insecticide puissant | Danger: Toxique'),
  ('anti-nuisibles', 'Anti-Fourmis & Cafards', 'Cypermethrine (concentre)', 'Base insecticide residuel | Danger: Toxique'),
  ('anti-nuisibles', 'Anti-Fourmis & Cafards', 'Fipronil (concentre)', 'Base appats gel | Danger: Toxique, usage encadre'),
  ('anti-nuisibles', 'Raticides & Rongeurs', 'Bromadiolone (concentre)', 'Base raticide anticoagulant | Danger: Tres toxique, reglemente'),
  ('anti-nuisibles', 'Insecticides Maison', 'Piperonyl butoxide (PBO)', 'Synergiste (renforce effet) | Danger: Modere'),
  ('anti-nuisibles', 'Anti-Moustiques & Mouches', 'DEET (concentre)', 'Base repulsif corporel | Danger: Modere'),
  ('matieres-premieres', 'Désinfectants', 'TCCA (Trichloroisocyanurate)', 'Chlore stabilise piscine | Danger: Oxydant'),
  ('anti-nuisibles', 'Produits Agrivet', 'Sulfate de cuivre', 'Base algicide | Danger: Toxique aquatique'),
  ('matieres-premieres', 'Polymères & Résines', 'Polymeres floculants', 'Clarification eau | Danger: Faible'),
  ('matieres-premieres', 'Charges Minérales', 'Charbon actif (vrac)', 'Filtration | Danger: Faible'),
  ('matieres-premieres', 'Charges Minérales', 'Ceramique filtrante (vrac)', 'Filtration | Danger: Faible'),
  ('matieres-premieres', 'Parfums & Additifs', 'Saccharose (Sucre blanc raffiné / Sucre SP)', 'Édulcorant de base / agent de fermentation / humectant (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Glucose / Dextrose monohydraté', 'Sucre fermentescible direct / anticristallisant / substrat levures (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Fructose (Lévulose)', 'Édulcorant naturel haute douceur / anticristallisant (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Sirop de glucose-fructose (HFCS)', 'Édulcorant liquide industriel / stabilisant texture (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Stévia (Glycosides de stéviol E960)', 'Édulcorant naturel zéro calorie (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Aspartame (E951)', 'Édulcorant intense artificiel / boissons ''light'' (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Acésulfame de potassium (Ace-K / E950)', 'Édulcorant intense sans calories / résistant chaleur (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Sucralose (E955)', 'Édulcorant intense 600× / stable chaleur et pH (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Saccharine sodique (E954)', 'Édulcorant intense artificiel / boissons et produits ''light'' / diététique (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Sorbitol (E420)', 'Édulcorant / humectant / anticristallisant (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Maltodextrine', 'Agent de charge / épaississant / support arômes séchage spray (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Acide citrique monohydraté (E330)', 'Acidifiant universel / antioxydant / séquestrant métaux (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Acide tartrique L(+) (E334)', 'Acidifiant vin / levant chimique (avec bicarbonate) / confiserie (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Acide citrique anhydre (E330)', 'Version anhydre — plus concentrée, hygroscopique moindre (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Acide malique DL (E296)', 'Acidifiant fruité / arôme pomme-poire / vinification (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Acide phosphorique H₃PO₄ (E338)', 'Acidifiant signature des colas / correction pH eau de brassage (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Acide acétique / Vinaigre blanc (E260)', 'Conservation par acidification / arôme vinaigrette / formation esters (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Carbonate de calcium CaCO₃ (E170)', 'Désacidifiant / antiagglomérant / source de calcium (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Bicarbonate de sodium NaHCO₃ (E500ii)', 'Agent levant / régulateur pH / désacidifiant doux (qualité alimentaire)'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Métabisulfite de potassium (E224) — ''Meta K''', 'Antiseptique / antioxydant majeur vin et jus (qualité alimentaire)'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Acide ascorbique / Ascorbate Na (E300/E301)', 'Antioxydant universel / fixateur couleur / acidifiant doux (qualité alimentaire)'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Acide sorbique (E200)', 'Conservateur antifongique naturel / forme acide du sorbate (qualité alimentaire)'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Nitrite de sodium / Sel nitrité (E250)', 'Conservation charcuterie / couleur rose / anti-botulisme (qualité alimentaire)'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Salpêtre / Nitrate de potassium (E252)', 'Conservation traditionnelle charcuterie / maturation saucisses sèches (qualité alimentaire)'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Lysozyme (E1105)', 'Inhibiteur bactéries lactiques vin / conservateur fromage (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Gélatine alimentaire en poudre (200 Bloom)', 'Gélifiant animal thermoreversible / clarification / texture (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Agar-Agar (E406)', 'Gélifiant végétal algues rouges / gel ferme thermostable (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Carraghénanes (E407)', 'Épaississant algues rouges / stabilisant lait / gel laitier (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Pectine HM (E440i)', 'Gélifiant naturel fruits / confiture haute teneur sucre (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Gomme arabique (E414)', 'Stabilisant émulsion arômes / encapsulation / collage vin (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Gomme guar (E412)', 'Épaississant économique / stabilisant glaces / sauces (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'CMC / Carboxyméthylcellulose (E466) — Tylose', 'Liant pâte à sucre / stabilisant vin / anti-cristal glaces (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Glycérine / Glycérol alimentaire (E422)', 'Humectant / corps en bouche / plasticifiant / anticristallisant (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Amidon natif (maïs, tapioca, pomme de terre)', 'Épaississant de base / liant / texture (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Amidon modifié (E1400–E1452)', 'Épaississant résistant chaleur / acides / congélation-décongélation (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Lécithine de soja (E322)', 'Émulsifiant universel / agent de surface / dispersant (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Mono- et diglycérides d''acides gras (E471)', 'Émulsifiant / stabilisant aération / texture gras (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Tripolyphosphate de sodium STPP (E451)', 'Rétention eau / texture viande / émulsification fromage fondu (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Plasmal (mélange phosphates alimentaires)', 'Rétention eau / liant / texture saucisse et produits carnés (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Polysorbate 80 (E433)', 'Émulsifiant synthétique / stabilisant glaces / solubilisant arômes (qualité alimentaire)'),
  ('matieres-premieres', 'Colorants', 'Caramel alimentaire (E150a — classe I)', 'Colorant brun / arôme / standardisation couleur (qualité alimentaire)'),
  ('matieres-premieres', 'Colorants', 'Colorant rouge ponceau 4R (E124)', 'Colorant rouge vif / sodas / confiserie (qualité alimentaire)'),
  ('matieres-premieres', 'Colorants', 'Colorant rouge vin / anthocyanes (E163)', 'Colorant rouge-violet naturel / correction couleur vin / boissons (qualité alimentaire)'),
  ('matieres-premieres', 'Colorants', 'Tartrazine jaune citron (E102)', 'Colorant jaune vif / sodas limon / pâtisserie (qualité alimentaire)'),
  ('matieres-premieres', 'Colorants', 'Bleu brillant FCF (E133)', 'Colorant bleu vif / combiné avec E102 → vert (qualité alimentaire)'),
  ('matieres-premieres', 'Colorants', 'Jaune orangé S (E110)', 'Colorant orange / sodas orange / confiserie (qualité alimentaire)'),
  ('matieres-premieres', 'Colorants', 'Dioxyde de titane (E171)', 'Colorant blanc / opacifiant / brillance glaçages (qualité alimentaire)'),
  ('matieres-premieres', 'Colorants', 'Bétacarotène (E160a)', 'Colorant orange-jaune naturel / précurseur Vit. A (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Dioxyde de carbone CO₂ alimentaire', 'Carbonatation des sodas, eaux gazeuses et bière (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Caféine (anhydre)', 'Stimulant / exhausteur amertume / signature boissons énergisantes (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Taurine', 'Acide aminé / boissons énergisantes / antioxydant endogène (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Inositol / Myo-inositol (Vitamine B8)', 'Cofacteur métabolique / boissons fonctionnelles (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Vitamines B3, B6, B12 (niacine, pyridoxine, cobalamine)', 'Enrichissement nutritionnel / boissons fonctionnelles et énergisantes (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Arôme naturel de fruits (concentré)', 'Parfumage / identité organoleptique / correction arôme (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Chlorure de calcium CaCl₂ alimentaire', 'Affermissement caillé fromage / raffermissement légumes conserve (qualité alimentaire)'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Sel nitrité (0.6% NaNO₂ dans NaCl)', 'Salaison / conservation / couleur rose / anti-botulisme (qualité alimentaire)'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Salpêtre (Nitrate de potassium KNO₃ E252)', 'Conservation longue durée / jambon sec / saucissons à maturation (qualité alimentaire)'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Ascorbate de sodium (E301)', 'Fixateur couleur charcuterie / accélérateur salaison / antioxydant (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Levure chimique (poudre à lever)', 'Agent levant / développement texture aérée gâteaux (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Crème de tartre (Tartrate acide de potassium E336)', 'Stabilisant blancs en neige / acide pour levant / régulateur pH meringue (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Tylose CMC (Pâtisserie décorative)', 'Durcissant pâte à sucre / fleurs en sucre / modelage décoratif (qualité alimentaire)'),
  ('matieres-premieres', 'Huiles & Beurres Cosmétiques', 'Glycérine pure alimentaire (E422)', 'Humectant / plasticifiant pâte à sucre / moelleux prolongé (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Soude caustique NaOH (grade alimentaire)', 'Nettoyage alcalin CIP / dégraissage / hydrolyse organique (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Acide phosphorique H₃PO₄ alimentaire (E338)', 'Détartrage acide CIP / dissolution dépôts calcaires (qualité alimentaire)'),
  ('matieres-premieres', 'Désinfectants', 'Acide peracétique (PAA)', 'Désinfectant puissant à froid / bactéricide-fongicide-virucide (qualité alimentaire)'),
  ('matieres-premieres', 'Désinfectants', 'Hypochlorite de sodium NaClO (eau de Javel)', 'Désinfection eau de process / surfaces / matériel (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Acide nitrique dilué HNO₃ (nettoyage inox)', 'Détartrage inox / dissolution dépôts minéraux tenaces (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Extrait de vanille naturel (Bourbon)', 'Arôme premium / note crémeuse-boisée (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Vanilline de synthèse (éthylvanilline)', 'Arôme vanille économique / dosage précis (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Glutamate monosodique MSG (E621)', 'Exhausteur de goût umami / amplificateur saveurs (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Caféine anhydre', 'Stimulant / amertume / signature energy drinks (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Acide citrique + Sorbate K — combo conservateur standard', 'Protection complète pH-dépendante / conservation économique (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Épices alimentaires (cannelle, muscade, gingembre, clou de girofle)', 'Aromatisation naturelle / propriétés antimicrobiennes (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Houblon — pellets T90 et extrait CO₂', 'Amertume / arôme / conservation naturelle bière (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Extrait de malt liquide / poudre', 'Base sucrée et aromatique / corps de la bière (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Pectine HM rapide (Extra-Rapide/Rapide)', 'Gélifiant confiture haute teneur en sucre / prise rapide (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Pectine LM (Faible méthylation) / Amidée', 'Gélifiant confitures allégées / produits sans sucre / laitier (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Chlorure de calcium CaCl₂ (texturation conserves)', 'Raffermissement légumes en conserve / activation pectinique (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Vinaigre blanc / Acide acétique (acidification conserves)', 'Conservation par acidification / cornichons / pickles (qualité alimentaire)'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Benzoate de sodium + Sorbate de K (combo conserves)', 'Conservation élargie anti-moisissures + antibactérien (qualité alimentaire)'),
  ('matieres-premieres', 'Chélatants', 'EDTA disodique (E385)', 'Séquestrant métaux / stabilisant couleur et saveur conserves (qualité alimentaire)'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Sulfite de sodium / Métabisulfite de sodium (E221/E223)', 'Antioxydant / agent de blanchiment / anti-brunissement fruits secs (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'Stabilisateur glace (combo gommes)', 'Anti-cristallisation / texture crémeuse / tenue à la fonte (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Saccharose inverti (Trimoline)', 'Abaissement point de congélation / texture souple à froid (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Dextrose (glucose anhydre pour glaces)', 'Abaissement point congélation / anticristallisant / texture (qualité alimentaire)'),
  ('matieres-premieres', 'Parfums & Additifs', 'Sirop de glucose (DE 38–42)', 'Anticristallisant / épaississant / corps / tenue à la fonte (qualité alimentaire)'),
  ('matieres-premieres', 'Charges Minérales', 'Bentonite œnologique (clarification vin)', 'Clarification protéique / collage / stabilisation thermique vin (qualité alimentaire)'),
  ('matieres-premieres', 'Épaississants', 'CMC alimentaire (stabilisation tartrique vin)', 'Inhibiteur cristallisation tartrate / alternative réfrigération (qualité alimentaire)'),
  ('matieres-premieres', 'Charges Minérales', 'Diatomite / Kieselguhr (filtration)', 'Filtration fine / clarification finale avant mise en bouteille (qualité alimentaire)'),
  ('matieres-premieres', 'Charges Minérales', 'Charbon actif œnologique (décoloration)', 'Décoloration / déodorisation / élimination excès tanins (qualité alimentaire)'),
  ('matieres-premieres', 'Colorants', 'Colorant caramel ammoniacal-sulfite (Classe IV — E150d)', 'Colorant brun-noir puissant, seul autorisé pour les colas et sodas acides au H₃PO₄ (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Citrate de sodium / Citrate de potassium (E331/E332)', 'Regulateur d''acidite / tampon pH / sequestrant — stabilise le gout acide des boissons gazeuses (qualité alimentaire)'),
  ('matieres-premieres', 'Acides & Bases', 'Acide fumarique (E297)', 'Acidifiant economique — alternative a l''acide citrique/tartrique pour poudres a diluer (qualité alimentaire)'),
  ('matieres-premieres', 'Conservateurs & Antioxydants', 'Nisine (E234)', 'Conservateur biologique a large spectre — bacteries Gram+ (Listeria, Clostridium botulinum) (qualité alimentaire)'),
  ('matieres-premieres', 'Charges Minérales', 'Silice colloïdale / Dioxyde de silicium (E551)', 'Anti-agglomerant / agent d''ecoulement pour poudres et sirops en sachet (qualité alimentaire)'),
  ('matieres-premieres', 'Désinfectants', 'Peroxyde d''hydrogène alimentaire (H₂O₂) — grade stérilisation emballage', 'Agent sterilisant des emballages aseptiques (type Tetra Pak / gourdes) avant remplissage a froid (qualité alimentaire)'),
  ('matieres-premieres', 'Charges Minérales', 'Sel de table / Chlorure de sodium alimentaire (NaCl)', 'Exhausteur de gout / conservateur traditionnel / regulateur osmotique (qualité alimentaire)')
on conflict (business_unit_slug, category_name, name) do nothing;
