-- ============================================================
-- AkoraHub - Patch Phase 230 : journal des recherches du catalogue site
-- web
--
-- Contexte (08/09) : demande explicite — savoir ce que les visiteurs
-- tapent dans la barre de recherche de catalogue.html, notamment les
-- recherches à 0 résultat, révélatrices d'une demande pour un produit
-- absent du catalogue.
--
-- Une ligne par recherche "stabilisée" (débattue côté client, voir
-- catalogue.html logSearchDebounced — pas une ligne par caractère
-- tapé), avec le nombre de résultats trouvés à ce moment-là.
--
-- Insertion directe depuis le navigateur (pas de Cloudflare Pages
-- Function comme pour site_visits/track-visit.js : aucune donnée
-- serveur comme le pays n'est utile ici) — RLS insert-only pour
-- anon/authenticated, lecture réservée à l'admin.
--
-- À exécuter une seule fois : Supabase Dashboard -> SQL Editor -> New
-- query. Idempotent (create if not exists).
-- ============================================================

create table if not exists public.catalogue_searches (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  query text not null,
  results_count integer,
  session_id text
);

create index if not exists catalogue_searches_created_at_idx on public.catalogue_searches (created_at);
create index if not exists catalogue_searches_query_idx on public.catalogue_searches (lower(query));

alter table public.catalogue_searches enable row level security;

drop policy if exists "catalogue_searches_insert_all" on public.catalogue_searches;
create policy "catalogue_searches_insert_all" on public.catalogue_searches
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "catalogue_searches_select_admin" on public.catalogue_searches;
create policy "catalogue_searches_select_admin" on public.catalogue_searches
  for select
  to authenticated
  using (public.current_role_is_admin());

-- Vérification : la table existe, RLS active, 2 policies (insert + select admin).
select policyname, cmd, roles from pg_policies where tablename = 'catalogue_searches';
